// Copyright 2025 fsyyft-ai
//
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mcp_time

import (
	"github.com/fsyyft-ai/mcp-time/internal/config"
	"github.com/fsyyft-ai/mcp-time/internal/task"
)

// Injectors from wire.go:

func wireServer(cfg *config.Config) (task.MCPTimeTask, func(), error) {
	logLogger, cleanup, err := NewLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	mcpTimeTask := task.NewMCPTimeTask(logLogger, cfg)
	return mcpTimeTask, func() {
		cleanup()
	}, nil
}
